- alias: Check sensor value and show notification
  trigger:
    platform: numeric_state
    entity_id: sensor.random_sensor
    above: 10
  action:
    service: persistent_notification.create
    data:
      message: "Sensor value greater than 10"