- alias: Check sensor value and show notification
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_158d00022ca9da
    above: 80
  action:
    service: notify.Telegram_Notifier_General
    data:
      title: 'Humidity @ Bathroom over 80%'
      message: "Humidity @ Bathroom is {{ states.sensor.humidity_158d00022ca9da.state }}%. Think about ventilating the appartment :)"'


