- platform: yeelight
    devices:
      192.168.1.149:
        name: Habitacion_Fer_y_Cris
        transition: 1000
        save_on_change: False #(defaults to True)

- platform: xiaomi_aqara
    devices:
      name: Luz Gateway Salon
      unique_id: rgb7811dcb23fec
