- platform: xiaomi_aqara
    name: Humedad Cuarto de Banho
    unique_id: humidity158d00022ca9da

- platform: xiaomi_aqara
    name: Iluminacion Gateway Salon
    unique_id: illumination7811dcb23fec

- platform: xiaomi_aqara
    name: Presion Cuarto de Banho
    unique_id: pressure158d00022ca9da

- platform: xiaomi_aqara
    name: Temperatura Cuarto de Banho
    unique_id: temperature158d00022ca9da